// app/layout.jsx
import { MuseoModerno } from "next/font/google"; // Asegúrate de reemplazar esto con el nombre correcto
import "./globals.css";
import { Providers } from "./providers";

const museoModerno = MuseoModerno({ subsets: ["latin"] }); // Cambia a la fuente que has elegido

export const metadata = {
  title: "HorarioJulian",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={museoModerno.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}


